name: CI

on:
  push:
    branches:
      - master
      - 'feature/*'
      - 'dependabot/*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup Node v16
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16

      - name: Test
        env:
          HPDF_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm ci
          npm run lint
          npm run build
          npm run test

      - name: Publish
        if: github.ref == 'refs/heads/master'
        uses: JS-DevTools/npm-publish@v1
        env:
          HPDF_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          token: ${{ secrets.NPM_TOKEN }}